apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-critical
  namespace: production-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mission-critical
  template:
    metadata:
      labels:
        app: mission-critical
    spec:
      containers:
      - name: web
        image: nginx:alpine
