import { apiRequest } from './client'

/**
 * Typed client for the FS-004 assignment endpoints (D-011).
 *
 * Assignments are user-bound invitations: the backend stores them through the
 * same invitation/token flow and exposes both an admin surface and the current
 * user's own list. Types are hand-written (not sourced from the generated
 * `schema.d.ts`) because `openapi.json` is regenerated by the orchestrator.
 */
export interface Assignment {
  id: string
  username: string
  preset: string
  assigned_by: string
  status: string
  created_at: string
  url: string
}

export interface AssignmentListResponse {
  assignments: Assignment[]
  total: number
}

export interface AssignmentCreateResponse {
  status: string
  assignment: Assignment
}

export function listAdminAssignments(): Promise<AssignmentListResponse> {
  return apiRequest<AssignmentListResponse>('/api/admin/assignments')
}

export function createAssignment(
  username: string,
  preset: string,
): Promise<AssignmentCreateResponse> {
  return apiRequest<AssignmentCreateResponse>('/api/admin/assignments', {
    method: 'POST',
    body: { username, preset },
  })
}

export function deleteAssignment(id: string): Promise<{ status: string; id: string }> {
  return apiRequest<{ status: string; id: string }>(
    `/api/admin/assignments/${encodeURIComponent(id)}`,
    { method: 'DELETE' },
  )
}

export function listMyAssignments(): Promise<AssignmentListResponse> {
  return apiRequest<AssignmentListResponse>('/api/assignments')
}
